package mapping

// NameToIso maps Portuguese country names to ISO 3166-1 Alpha-3 codes
var NameToIso = map[string]string{
	"Afeganistão":                   "AFG",
	"África do Sul":                 "ZAF",
	"Alasca":                        "USA",
	"Albânia":                       "ALB",
	"Alemanha":                      "DEU",
	"Andorra":                       "AND",
	"Angola":                        "AGO",
	"Antígua e Barbuda":             "ATG",
	"Arábia Saudita":                "SAU",
	"Argélia":                       "DZA",
	"Argentina":                     "ARG",
	"Armênia":                       "ARM",
	"Austrália":                     "AUS",
	"Áustria":                       "AUT",
	"Azerbaijão":                    "AZE",
	"Azerbajão":                     "AZE", // Variação de grafia usada pelo Maratona.app
	"Bahamas":                       "BHS",
	"Bahrein":                       "BHR",
	"Bangladesh":                    "BGD",
	"Barbados":                      "BRB",
	"Bélgica":                       "BEL",
	"Belize":                        "BLZ",
	"Benin":                         "BEN",
	"Bielorrússia":                  "BLR",
	"Bolívia":                       "BOL",
	"Bósnia-Herzegóvina":            "BIH",
	"Botsuana":                      "BWA",
	"Brasil":                        "BRA",
	"Brunei":                        "BRN",
	"Bulgária":                      "BGR",
	"Burkina Faso":                  "BFA",
	"Burundi":                       "BDI",
	"Butão":                         "BTN",
	"Cabo Verde":                    "CPV",
	"Cabo verde":                    "CPV", // Variação de capitalização usada pelo Maratona.app
	"Camarões":                      "CMR",
	"Camboja":                       "KHM",
	"Canadá":                        "CAN",
	"Catar":                         "QAT",
	"Cazaquistão":                   "KAZ",
	"Chade":                         "TCD",
	"Chile":                         "CHL",
	"China":                         "CHN",
	"Chipre":                        "CYP",
	"Colômbia":                      "COL",
	"Comores":                       "COM",
	"Congo":                         "COG",
	"Coreia do Norte":               "PRK",
	"Coreia do Sul":                 "KOR",
	"Costa do Marfim":               "CIV",
	"Costa Rica":                    "CRI",
	"Croácia":                       "HRV",
	"Cuba":                          "CUB",
	"Dinamarca":                     "DNK",
	"Djibouti":                      "DJI",
	"Dominica":                      "DMA",
	"Egito":                         "EGY",
	"El Salvador":                   "SLV",
	"Emirados Árabes Unidos":        "ARE",
	"Emirados Árabes":               "ARE", // Variação curta usada pelo Maratona.app
	"Equador":                       "ECU",
	"Eritreia":                      "ERI",
	"Eslováquia":                    "SVK",
	"Eslovênia":                     "SVN",
	"Espanha":                       "ESP",
	"Essuatíni":                     "SWZ",
	"Estados Unidos":                "USA",
	"Estônia":                       "EST",
	"Etiópia":                       "ETH",
	"Fiji":                          "FJI",
	"Filipinas":                     "PHL",
	"Finlândia":                     "FIN",
	"França":                        "FRA",
	"Gabão":                         "GAB",
	"Gâmbia":                        "GMB",
	"Gana":                          "GHA",
	"Geórgia":                       "GEO",
	"Granada":                       "GRD",
	"Grécia":                        "GRC",
	"Groelândia":                    "GRL",
	"Guatemala":                     "GTM",
	"Guiana":                        "GUY",
	"Guiana Francesa":               "GUF",
	"Guiné":                         "GIN",
	"Guiné Equatorial":              "GNQ",
	"Guiné-Bissau":                  "GNB",
	"Haiti":                         "HTI",
	"Honduras":                      "HND",
	"Hungria":                       "HUN",
	"Iêmen":                         "YEM",
	"Ilhas Marshall":                "MHL",
	"Ilhas Salomão":                 "SLB",
	"Índia":                         "IND",
	"Indonésia":                     "IDN",
	"Irã":                           "IRN",
	"Iraque":                        "IRQ",
	"Irlanda":                       "IRL",
	"Islândia":                      "ISL",
	"Israel":                        "ISR",
	"Itália":                        "ITA",
	"Jamaica":                       "JAM",
	"Japão":                         "JPN",
	"Jordânia":                      "JOR",
	"Kiribati":                      "KIR",
	"Kuwait":                        "KWT",
	"Laos":                          "LAO",
	"Lesoto":                        "LSO",
	"Letônia":                       "LVA",
	"Líbano":                        "LBN",
	"Libéria":                       "LBR",
	"Líbia":                         "LBY",
	"Liechtenstein":                 "LIE",
	"Lituânia":                      "LTU",
	"Luxemburgo":                    "LUX",
	"Macedônia do Norte":            "MKD",
	"Madagascar":                    "MDG",
	"Malásia":                       "MYS",
	"Malawi":                        "MWI",
	"Maldivas":                      "MDV",
	"Mali":                          "MLI",
	"Malta":                         "MLT",
	"Marrocos":                      "MAR",
	"Maurício":                      "MUS",
	"Mauritânia":                    "MRT",
	"México":                        "MEX",
	"Mianmar":                       "MMR",
	"Micronésia":                    "FSM",
	"Moçambique":                    "MOZ",
	"Moldávia":                      "MDA",
	"Mônaco":                        "MCO",
	"Mongólia":                      "MNG",
	"Montenegro":                    "MNE",
	"Montserrat":                    "MSR",
	"Namíbia":                       "NAM",
	"Nauru":                         "NRU",
	"Nepal":                         "NPL",
	"Nicarágua":                     "NIC",
	"Níger":                         "NER",
	"Nigéria":                       "NGA",
	"Noruega":                       "NOR",
	"Nova Zelândia":                 "NZL",
	"Omã":                           "OMN",
	"Países Baixos":                 "NLD",
	"Palau":                         "PLW",
	"Palestina":                     "PSE",
	"Panamá":                        "PAN",
	"Papua-Nova Guiné":              "PNG",
	"Paquistão":                     "PAK",
	"Paraguai":                      "PRY",
	"Peru":                          "PER",
	"Polônia":                       "POL",
	"Porto Rico":                    "PRI",
	"Portugal":                      "PRT",
	"Quênia":                        "KEN",
	"Quirguistão":                   "KGZ",
	"Reino Unido":                   "GBR",
	"Inglaterra":                    "GBR",
	"Escócia":                       "GBR",
	"País de Gales":                 "GBR",
	"Irlanda do Norte":              "GBR",
	"Irlanda do norte":              "GBR", // Variação de capitalização usada pelo Maratona.app
	"República Centro-Africana":     "CAF",
	"República Democrática do Congo": "COD",
	"República Dominicana":          "DOM",
	"Romênia":                       "ROU",
	"Ruanda":                        "RWA",
	"Rússia":                        "RUS",
	"Saara Ocidental":               "ESH",
	"Samoa":                         "WSM",
	"San Marino":                    "SMR",
	"Santa Lúcia":                   "LCA",
	"São Cristóvão e Névis":         "KNA",
	"São Tomé e Príncipe":           "STP",
	"São Vicente e Grandinas":       "VCT",
	"Senegal":                       "SEN",
	"Serra Leoa":                    "SLE",
	"Sérvia":                        "SRB",
	"Seychelles":                    "SYC",
	"Singapura":                     "SGP",
	"Síria":                         "SYR",
	"Somália":                       "SOM",
	"Sri Lanka":                     "LKA",
	"Suazilândia":                   "SWZ",
	"Sudão":                         "SDN",
	"Sudão do Sul":                  "SSD",
	"Suécia":                        "SWE",
	"Suíça":                         "CHE",
	"Suiça":                         "CHE", // Variação sem acento usada pelo Maratona.app
	"Suriname":                      "SUR",
	"Tailândia":                     "THA",
	"Taiwan":                        "TWN",
	"Tajiquistão":                   "TJK",
	"Tanzânia":                      "TZA",
	"Tchéquia":                      "CZE",
	"Timor Leste":                   "TLS",
	"Togo":                          "TGO",
	"Tonga":                         "TON",
	"Trindade e Tobago":             "TTO",
	"Tunísia":                       "TUN",
	"Turcomenistão":                 "TKM",
	"Turquia":                       "TUR",
	"Tuvalu":                        "TUV",
	"Ucrânia":                       "UKR",
	"Uganda":                        "UGA",
	"Uruguai":                       "URY",
	"Uzbequistão":                   "UZB",
	"Vanuatu":                       "VUT",
	"Vaticano":                      "VAT",
	"Venezuela":                     "VEN",
	"Vietnã":                        "VNM",
	"Zâmbia":                        "ZMB",
	"Zimbábue":                      "ZWE",
}

// GetISO returns the ISO code for a country name, or empty string if not found
func GetISO(countryName string) string {
	if iso, ok := NameToIso[countryName]; ok {
		return iso
	}
	return ""
}
