/**
 * Mapping of ISO 3166-1 Alpha-3 codes to Portuguese country names
 * @type {Object<string, string>}
 */
export const countryNames = {
  'AFG': 'Afeganistão',
  'ZAF': 'África do Sul',
  'USA': 'Estados Unidos',
  'ALB': 'Albânia',
  'DEU': 'Alemanha',
  'AND': 'Andorra',
  'AGO': 'Angola',
  'ATG': 'Antígua e Barbuda',
  'SAU': 'Arábia Saudita',
  'DZA': 'Argélia',
  'ARG': 'Argentina',
  'ARM': 'Armênia',
  'AUS': 'Austrália',
  'AUT': 'Áustria',
  'AZE': 'Azerbaijão',
  'BHS': 'Bahamas',
  'BHR': 'Bahrein',
  'BGD': 'Bangladesh',
  'BRB': 'Barbados',
  'BEL': 'Bélgica',
  'BLZ': 'Belize',
  'BEN': 'Benin',
  'BLR': 'Bielorrússia',
  'BOL': 'Bolívia',
  'BIH': 'Bósnia-Herzegóvina',
  'BWA': 'Botsuana',
  'BRA': 'Brasil',
  'BRN': 'Brunei',
  'BGR': 'Bulgária',
  'BFA': 'Burkina Faso',
  'BDI': 'Burundi',
  'BTN': 'Butão',
  'CPV': 'Cabo Verde',
  'CMR': 'Camarões',
  'KHM': 'Camboja',
  'CAN': 'Canadá',
  'QAT': 'Catar',
  'KAZ': 'Cazaquistão',
  'TCD': 'Chade',
  'CHL': 'Chile',
  'CHN': 'China',
  'CYP': 'Chipre',
  'COL': 'Colômbia',
  'COM': 'Comores',
  'COG': 'Congo',
  'PRK': 'Coreia do Norte',
  'KOR': 'Coreia do Sul',
  'CIV': 'Costa do Marfim',
  'CRI': 'Costa Rica',
  'HRV': 'Croácia',
  'CUB': 'Cuba',
  'DNK': 'Dinamarca',
  'DJI': 'Djibouti',
  'DMA': 'Dominica',
  'EGY': 'Egito',
  'SLV': 'El Salvador',
  'ARE': 'Emirados Árabes Unidos',
  'ECU': 'Equador',
  'ERI': 'Eritreia',
  'SVK': 'Eslováquia',
  'SVN': 'Eslovênia',
  'ESP': 'Espanha',
  'SWZ': 'Essuatíni',
  'EST': 'Estônia',
  'ETH': 'Etiópia',
  'FJI': 'Fiji',
  'PHL': 'Filipinas',
  'FIN': 'Finlândia',
  'FRA': 'França',
  'GAB': 'Gabão',
  'GMB': 'Gâmbia',
  'GHA': 'Gana',
  'GEO': 'Geórgia',
  'GRD': 'Granada',
  'GRC': 'Grécia',
  'GRL': 'Groelândia',
  'GTM': 'Guatemala',
  'GUY': 'Guiana',
  'GUF': 'Guiana Francesa',
  'GIN': 'Guiné',
  'GNQ': 'Guiné Equatorial',
  'GNB': 'Guiné-Bissau',
  'HTI': 'Haiti',
  'HND': 'Honduras',
  'HUN': 'Hungria',
  'YEM': 'Iêmen',
  'MHL': 'Ilhas Marshall',
  'SLB': 'Ilhas Salomão',
  'IND': 'Índia',
  'IDN': 'Indonésia',
  'IRN': 'Irã',
  'IRQ': 'Iraque',
  'IRL': 'Irlanda',
  'ISL': 'Islândia',
  'ISR': 'Israel',
  'ITA': 'Itália',
  'JAM': 'Jamaica',
  'JPN': 'Japão',
  'JOR': 'Jordânia',
  'KIR': 'Kiribati',
  'KWT': 'Kuwait',
  'LAO': 'Laos',
  'LSO': 'Lesoto',
  'LVA': 'Letônia',
  'LBN': 'Líbano',
  'LBR': 'Libéria',
  'LBY': 'Líbia',
  'LIE': 'Liechtenstein',
  'LTU': 'Lituânia',
  'LUX': 'Luxemburgo',
  'MKD': 'Macedônia do Norte',
  'MDG': 'Madagascar',
  'MYS': 'Malásia',
  'MWI': 'Malawi',
  'MDV': 'Maldivas',
  'MLI': 'Mali',
  'MLT': 'Malta',
  'MAR': 'Marrocos',
  'MUS': 'Maurício',
  'MRT': 'Mauritânia',
  'MEX': 'México',
  'MMR': 'Mianmar',
  'FSM': 'Micronésia',
  'MOZ': 'Moçambique',
  'MDA': 'Moldávia',
  'MCO': 'Mônaco',
  'MNG': 'Mongólia',
  'MNE': 'Montenegro',
  'MSR': 'Montserrat',
  'NAM': 'Namíbia',
  'NRU': 'Nauru',
  'NPL': 'Nepal',
  'NIC': 'Nicarágua',
  'NER': 'Níger',
  'NGA': 'Nigéria',
  'NOR': 'Noruega',
  'NZL': 'Nova Zelândia',
  'OMN': 'Omã',
  'NLD': 'Países Baixos',
  'PLW': 'Palau',
  'PSE': 'Palestina',
  'PAN': 'Panamá',
  'PNG': 'Papua-Nova Guiné',
  'PAK': 'Paquistão',
  'PRY': 'Paraguai',
  'PER': 'Peru',
  'POL': 'Polônia',
  'PRI': 'Porto Rico',
  'PRT': 'Portugal',
  'KEN': 'Quênia',
  'KGZ': 'Quirguistão',
  'GBR': 'Reino Unido',
  'CAF': 'República Centro-Africana',
  'COD': 'República Democrática do Congo',
  'DOM': 'República Dominicana',
  'ROU': 'Romênia',
  'RWA': 'Ruanda',
  'RUS': 'Rússia',
  'ESH': 'Saara Ocidental',
  'WSM': 'Samoa',
  'SMR': 'San Marino',
  'LCA': 'Santa Lúcia',
  'KNA': 'São Cristóvão e Névis',
  'STP': 'São Tomé e Príncipe',
  'VCT': 'São Vicente e Grandinas',
  'SEN': 'Senegal',
  'SLE': 'Serra Leoa',
  'SRB': 'Sérvia',
  'SYC': 'Seychelles',
  'SGP': 'Singapura',
  'SYR': 'Síria',
  'SOM': 'Somália',
  'LKA': 'Sri Lanka',
  'SDN': 'Sudão',
  'SSD': 'Sudão do Sul',
  'SWE': 'Suécia',
  'CHE': 'Suíça',
  'SUR': 'Suriname',
  'THA': 'Tailândia',
  'TWN': 'Taiwan',
  'TJK': 'Tajiquistão',
  'TZA': 'Tanzânia',
  'CZE': 'Tchéquia',
  'TLS': 'Timor Leste',
  'TGO': 'Togo',
  'TON': 'Tonga',
  'TTO': 'Trindade e Tobago',
  'TUN': 'Tunísia',
  'TKM': 'Turcomenistão',
  'TUR': 'Turquia',
  'TUV': 'Tuvalu',
  'UKR': 'Ucrânia',
  'UGA': 'Uganda',
  'URY': 'Uruguai',
  'UZB': 'Uzbequistão',
  'VUT': 'Vanuatu',
  'VAT': 'Vaticano',
  'VEN': 'Venezuela',
  'VNM': 'Vietnã',
  'ZMB': 'Zâmbia',
  'ZWE': 'Zimbábue',
}

/**
 * Get Portuguese country name from ISO code
 * @param {string} iso - ISO 3166-1 Alpha-3 code
 * @returns {string} Country name in Portuguese or ISO code if not found
 */
export function getCountryName(iso) {
  return countryNames[iso] || iso
}
